"use client";

import { useState } from "react";
import { Check, CalendarDays, ShieldCheck } from "lucide-react";
import { useRouter } from "next/navigation";
import { BillingCheckout, BillingHistory } from "./BillingCheckout";

declare global { interface Window { Razorpay?: new(options: Record<string, unknown>) => { open: () => void } } }
type Profile={legalName:string;email:string;phone:string;addressLine1:string;addressLine2:string;city:string;state:string;postalCode:string;country:string;gstin:string};
const plans = [
  { key: "FREE", name: "Free", price: 0, limit: "50", features: ["AI website agent", "Lead capture", "AARYVO branding"] },
  { key: "STARTER", name: "Starter", price: 999, limit: "500", features: ["Lead qualification", "Conversation inbox", "Appointments & alerts"] },
  { key: "GROWTH", name: "Growth", price: 2499, limit: "2,000", features: ["Follow-up workflow", "Google Calendar", "Custom widget branding"] },
  { key: "PRO", name: "Pro", price: 4999, limit: "5,000", features: ["Highest usage limit", "Priority support", "Future premium integrations"] },
];
function loadScript(){return new Promise<boolean>(resolve=>{if(window.Razorpay)return resolve(true);const s=document.createElement("script");s.src="https://checkout.razorpay.com/v1/checkout.js";s.onload=()=>resolve(true);s.onerror=()=>resolve(false);document.body.appendChild(s)})}function money(n:number){return `₹${n.toLocaleString("en-IN")}`}

export default function BillingClient({currentPlan,usage,limit,subscriptionStatus,currentPeriodEnd,cancelAtEnd,hasSubscription}:{currentPlan:string;usage:number;limit:number;subscriptionStatus:string;currentPeriodEnd:string|null;cancelAtEnd:boolean;hasSubscription:boolean}){
 const router=useRouter(),[loading,setLoading]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState(""),[checkoutPlan,setCheckoutPlan]=useState<(typeof plans)[number]|null>(null);const paid=currentPlan!=="FREE"&&hasSubscription,currentPrice=plans.find(p=>p.key===currentPlan)?.price||0,renewal=currentPeriodEnd?new Intl.DateTimeFormat("en-IN",{day:"numeric",month:"short",year:"numeric"}).format(new Date(currentPeriodEnd)):null;
 async function startCheckout(profile:Profile){if(!checkoutPlan)return;if(!(await loadScript()))throw Error("Unable to load secure checkout.");const r=await fetch("/api/billing/subscribe",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({plan:checkoutPlan.key,profile})}),d=await r.json();if(!r.ok)throw Error(d.error||"Unable to start checkout.");const rz=new window.Razorpay!({key:d.keyId,subscription_id:d.subscriptionId,name:"AARYVO",description:`${d.plan} monthly subscription`,prefill:{name:d.name,email:d.email,contact:d.phone},theme:{color:"#111319"},handler:()=>{setCheckoutPlan(null);setMessage("Payment received. Your subscription is being activated.");setTimeout(()=>router.refresh(),1200)}});rz.open()}
 async function subscribe(plan:string){setError("");setMessage("");const target=plans.find(p=>p.key===plan)!;if(!paid){setCheckoutPlan(target);return}setLoading(plan);try{const action=target.price>currentPrice?"upgrade":"downgrade";if(!window.confirm(`${action==="upgrade"?"Upgrade":"Downgrade"} to ${target.name} at ${money(target.price)}/month? ${action==="upgrade"?"The change will be requested now.":"The change will take effect at the end of the current billing cycle."}`))return;const r=await fetch("/api/billing/change-plan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({plan})}),d=await r.json();if(!r.ok)throw Error(d.error||"Unable to change plan.");setMessage(d.effective==="cycle_end"?`Downgrade to ${target.name} scheduled for the end of this billing cycle.`:`Plan changed to ${target.name}.`);router.refresh()}catch(e){setError(e instanceof Error?e.message:"Unable to update billing.")}finally{setLoading("")}}
 async function cancelSubscription(){if(!window.confirm(`Cancel your ${currentPlan} subscription at the end of the current billing period${renewal?` (${renewal})`:""}? You will keep access until then.`))return;setLoading("CANCEL");setError("");setMessage("");try{const r=await fetch("/api/billing/cancel",{method:"POST"}),d=await r.json();if(!r.ok)throw Error(d.error||"Unable to cancel subscription.");setMessage("Cancellation scheduled. Your paid access remains available until the end of the current billing period.");router.refresh()}catch(e){setError(e instanceof Error?e.message:"Unable to cancel subscription.")}finally{setLoading("")}}
 return <>{checkoutPlan&&<BillingCheckout plan={checkoutPlan} onClose={()=>setCheckoutPlan(null)} onCheckout={startCheckout}/>}<section className="mt-7 rounded-3xl bg-[#111319] p-6 text-white md:p-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs uppercase tracking-[.14em] text-white/35">Current plan</p><div className="mt-2 flex flex-wrap items-center gap-3"><h2 className="text-3xl font-semibold">{currentPlan}</h2><span className="rounded-full border border-white/15 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wider text-white/65">{cancelAtEnd?"Cancels at period end":subscriptionStatus}</span></div><p className="mt-2 text-sm text-white/45">{usage.toLocaleString("en-IN")} of {limit.toLocaleString("en-IN")} conversations used this billing period.</p></div><div className="w-full max-w-sm"><div className="h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-white" style={{width:`${Math.min(100,limit?usage/limit*100:0)}%`}}/></div><p className="mt-2 text-right text-[10px] text-white/35">{Math.max(0,limit-usage).toLocaleString("en-IN")} remaining</p></div></div></section>
 {paid&&<section className="mt-4 grid gap-3 md:grid-cols-2"><div className="rounded-2xl border border-black/[.06] bg-white p-5"><div className="flex items-center gap-3"><span className="rounded-xl bg-black/[.04] p-2.5"><ShieldCheck size={17}/></span><div><p className="text-xs text-black/40">Subscription status</p><p className="mt-0.5 text-sm font-semibold capitalize">{cancelAtEnd?"Cancellation scheduled":subscriptionStatus}</p></div></div></div><div className="rounded-2xl border border-black/[.06] bg-white p-5"><div className="flex items-center gap-3"><span className="rounded-xl bg-black/[.04] p-2.5"><CalendarDays size={17}/></span><div><p className="text-xs text-black/40">{cancelAtEnd?"Access until":"Next billing date"}</p><p className="mt-0.5 text-sm font-semibold">{renewal||"Awaiting billing cycle update"}</p></div></div></div></section>}
 {message&&<p className="mt-4 rounded-xl bg-emerald-50 p-3 text-xs text-emerald-800">{message}</p>}{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-xs text-red-700">{error}</p>}
 <section className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{plans.map(p=>{const isCurrent=currentPlan===p.key,isFree=p.key==="FREE",isUpgrade=p.price>currentPrice,label=isCurrent?"Current plan":isFree?"Free plan":paid?(isUpgrade?"Upgrade":"Downgrade"):"Choose plan";return <article key={p.key} className={`rounded-3xl border bg-white p-6 ${isCurrent?"border-black":"border-black/[.06]"}`}><div className="flex items-center justify-between"><h3 className="text-lg font-semibold">{p.name}</h3>{isCurrent&&<span className="rounded-full bg-black px-2.5 py-1 text-[9px] font-semibold text-white">CURRENT</span>}</div><p className="mt-5 text-3xl font-semibold tracking-[-.05em]">{money(p.price)}<span className="text-xs font-normal text-black/35"> /month</span></p>{!isFree&&<p className="mt-1 text-[10px] text-black/35">GST included</p>}<p className="mt-2 text-xs text-black/40">{p.limit} conversations / month</p><div className="my-5 h-px bg-black/[.06]"/><div className="space-y-3">{p.features.map(f=><p key={f} className="flex gap-2 text-xs text-black/55"><Check size={13}/>{f}</p>)}</div><button disabled={isFree||isCurrent||Boolean(loading)||cancelAtEnd} onClick={()=>subscribe(p.key)} className="mt-7 w-full rounded-xl bg-black px-4 py-3 text-xs font-semibold text-white disabled:bg-black/[.06] disabled:text-black/30">{loading===p.key?"Updating...":label}</button></article>})}</section>
 {paid&&<section className="mt-5 rounded-3xl border border-black/[.06] bg-white p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="text-sm font-semibold">Manage subscription</h3><p className="mt-1 text-xs leading-5 text-black/45">{cancelAtEnd?`Your subscription is scheduled to end${renewal?` on ${renewal}`:" at the end of the billing period"}.`:"Cancel recurring billing while keeping paid access through the current billing period."}</p></div>{!cancelAtEnd&&<button disabled={Boolean(loading)} onClick={cancelSubscription} className="rounded-xl border border-black/10 px-4 py-2.5 text-xs font-semibold text-black/60 hover:border-black/25 disabled:opacity-40">{loading==="CANCEL"?"Scheduling...":"Cancel subscription"}</button>}</div></section>}<BillingHistory/></>;
}
