"use client";
import { useState } from "react";

type Props={initial:{notificationEmail:string|null;bookingTimeZone:string;bookingSlotMinutes:number;bookingStartHour:number;bookingEndHour:number;bookingDaysAhead:number;bookingWorkingDays:string}};
const DAYS=[{v:1,l:"Mon"},{v:2,l:"Tue"},{v:3,l:"Wed"},{v:4,l:"Thu"},{v:5,l:"Fri"},{v:6,l:"Sat"},{v:0,l:"Sun"}];
export default function SettingsForm({initial}:Props){
 const[form,setForm]=useState({...initial,bookingWorkingDays:initial.bookingWorkingDays.split(",").map(Number)});const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");
 const toggle=(day:number)=>setForm(f=>({...f,bookingWorkingDays:f.bookingWorkingDays.includes(day)?f.bookingWorkingDays.filter(d=>d!==day):[...f.bookingWorkingDays,day]}));
 async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);setMessage("");try{const res=await fetch("/api/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const data=await res.json();if(!res.ok)throw new Error(data.error||"Unable to save settings.");setMessage("Settings saved. New booking slots will use these hours immediately.");}catch(error){setMessage(error instanceof Error?error.message:"Unable to save settings.");}finally{setSaving(false);}}
 const field="mt-2 w-full rounded-xl border border-black/10 bg-white px-4 py-3 text-sm outline-none focus:border-black/40";
 return <form onSubmit={submit} className="space-y-8">
  <section className="rounded-3xl border border-black/10 bg-white p-6 md:p-8"><h2 className="text-xl font-semibold">Notifications</h2><p className="mt-1 text-sm text-black/55">Where AARYVO should send new lead and appointment alerts.</p><label className="mt-6 block text-sm font-medium">Notification email<input className={field} type="email" value={form.notificationEmail||""} onChange={e=>setForm({...form,notificationEmail:e.target.value})} placeholder="sales@yourbusiness.com"/></label></section>
  <section className="rounded-3xl border border-black/10 bg-white p-6 md:p-8"><h2 className="text-xl font-semibold">Appointment availability</h2><p className="mt-1 text-sm text-black/55">These hours control the consultation slots visitors see in your AI sales agent.</p>
   <div className="mt-6"><span className="text-sm font-medium">Working days</span><div className="mt-3 flex flex-wrap gap-2">{DAYS.map(day=><button key={day.v} type="button" onClick={()=>toggle(day.v)} className={`rounded-full px-4 py-2 text-sm font-medium ${form.bookingWorkingDays.includes(day.v)?"bg-black text-white":"border border-black/10 bg-white text-black/60"}`}>{day.l}</button>)}</div></div>
   <div className="mt-6 grid gap-5 md:grid-cols-2"><label className="text-sm font-medium">Start hour<select className={field} value={form.bookingStartHour} onChange={e=>setForm({...form,bookingStartHour:Number(e.target.value)})}>{Array.from({length:24},(_,i)=><option key={i} value={i}>{String(i).padStart(2,"0")}:00</option>)}</select></label><label className="text-sm font-medium">End hour<select className={field} value={form.bookingEndHour} onChange={e=>setForm({...form,bookingEndHour:Number(e.target.value)})}>{Array.from({length:24},(_,i)=><option key={i+1} value={i+1}>{String(i+1).padStart(2,"0")}:00</option>)}</select></label></div>
   <div className="mt-5 grid gap-5 md:grid-cols-3"><label className="text-sm font-medium">Slot duration<select className={field} value={form.bookingSlotMinutes} onChange={e=>setForm({...form,bookingSlotMinutes:Number(e.target.value)})}>{[15,30,45,60].map(v=><option key={v} value={v}>{v} minutes</option>)}</select></label><label className="text-sm font-medium">Booking window<select className={field} value={form.bookingDaysAhead} onChange={e=>setForm({...form,bookingDaysAhead:Number(e.target.value)})}>{[7,14,21,30].map(v=><option key={v} value={v}>{v} days</option>)}</select></label><label className="text-sm font-medium">Timezone<select className={field} value={form.bookingTimeZone} onChange={e=>setForm({...form,bookingTimeZone:e.target.value})}><option value="Asia/Kolkata">India — Asia/Kolkata</option><option value="America/New_York">US Eastern — New York</option><option value="America/Chicago">US Central — Chicago</option><option value="America/Denver">US Mountain — Denver</option><option value="America/Los_Angeles">US Pacific — Los Angeles</option><option value="Europe/London">UK — London</option><option value="Europe/Berlin">Europe — Berlin</option><option value="Asia/Dubai">UAE — Dubai</option><option value="Asia/Singapore">Singapore</option><option value="Australia/Sydney">Australia — Sydney</option></select></label></div>
  </section>
  <div className="flex items-center gap-4"><button disabled={saving} className="rounded-full bg-black px-6 py-3 text-sm font-semibold text-white disabled:opacity-50">{saving?"Saving…":"Save settings"}</button>{message&&<p className="text-sm text-black/60">{message}</p>}</div>
 </form>;
}
