import Link from "next/link";
import LegalPage from "../_components/LegalPage";
export const metadata={title:"Terms of Service | AARYVO",description:"Terms of Service for AARYVO."};
const sections:Array<[string,string]>=[
["Using AARYVO","You must provide accurate account information, keep account credentials secure and use AARYVO only for lawful business purposes. You are responsible for your workspace configuration, website knowledge and the actions you take based on leads or AI-generated information."],
["AI-generated responses","AARYVO uses artificial intelligence and may occasionally produce incomplete or inaccurate responses. You should configure approved business knowledge and human handoff rules appropriately. AARYVO is a sales and workflow tool and should not be relied on as professional legal, medical, financial or emergency advice."],
["Visitor data","If you install AARYVO on a website, you are responsible for providing any notices and obtaining any permissions or consents required for collecting and processing visitor information. You must not intentionally submit unlawful or highly sensitive information that is not necessary for the service."],
["Subscriptions and usage","Paid plans are billed on a recurring basis through our payment provider and include plan-specific conversation limits. If you cancel recurring billing, paid access continues until the end of the paid billing period unless otherwise stated. At the end of that period the workspace may return to the Free plan and its applicable limits."],
["Availability and changes","We work to keep AARYVO reliable, but uninterrupted availability is not guaranteed. We may make reasonable changes required for security, legal compliance, provider compatibility or service improvement."],
["Acceptable use","You may not use AARYVO to violate law, infringe rights, distribute malware, attempt unauthorized access, abuse platform resources, impersonate others, or intentionally generate deceptive, fraudulent or harmful communications."],
["Intellectual property","AARYVO and its software, branding and platform materials remain the property of their respective owner. Customers retain their rights in business content they provide and grant us the rights necessary to process that content to operate the service."],
["Suspension and termination","We may suspend or restrict access when necessary to address security risks, unlawful use, abuse, non-payment or material violations of these terms. You may stop using AARYVO and manage an eligible paid subscription from the Billing area."],
["Liability","To the extent permitted by applicable law, AARYVO is provided without guarantees of specific sales outcomes. We are not responsible for indirect or consequential losses arising from reliance on AI output, third-party services or customer-controlled configurations."],
["Changes to these terms","We may update these terms as the service evolves. Continued use after an updated version becomes effective constitutes acceptance of the revised terms where permitted by law."],
];
export default function TermsPage(){return <LegalPage title="Terms of Service" effective="14 September 2026" intro="These Terms govern access to and use of AARYVO. By creating an account or using the service, you agree to these Terms." sections={sections} footerNote={<>Questions about these Terms? <Link href="/contact" className="font-semibold underline underline-offset-4">Contact us.</Link></>} />;}
