import crypto from "crypto";
import { prisma } from "@/lib/prisma";
import { ensureBillingTables, getBillingProfile, taxBreakdownInclusive } from "@/lib/billing-profile";
import { planFromRazorpayPlanId, razorpayRequest, type PlanKey } from "@/lib/billing";

export type StoredInvoice = {
  id:string;businessId:string;razorpayInvoiceId:string;razorpayPaymentId:string|null;razorpaySubscriptionId:string|null;invoiceNumber:string|null;plan:string;status:string;currency:string;subtotalPaise:number;taxPaise:number;cgstPaise:number;sgstPaise:number;igstPaise:number;totalPaise:number;taxRate:number;taxType:string;shortUrl:string|null;issuedAt:Date;paidAt:Date|null;legalName:string;email:string;phone:string;addressLine1:string;addressLine2:string|null;city:string;state:string;postalCode:string;country:string;gstin:string|null;supplierState:string|null;
};

function rowInvoice(row:Record<string,unknown>):StoredInvoice{return{id:String(row.id),businessId:String(row.businessId),razorpayInvoiceId:String(row.razorpayInvoiceId),razorpayPaymentId:row.razorpayPaymentId?String(row.razorpayPaymentId):null,razorpaySubscriptionId:row.razorpaySubscriptionId?String(row.razorpaySubscriptionId):null,invoiceNumber:row.invoiceNumber?String(row.invoiceNumber):null,plan:String(row.plan),status:String(row.status),currency:String(row.currency||"INR"),subtotalPaise:Number(row.subtotalPaise||0),taxPaise:Number(row.taxPaise||0),cgstPaise:Number(row.cgstPaise||0),sgstPaise:Number(row.sgstPaise||0),igstPaise:Number(row.igstPaise||0),totalPaise:Number(row.totalPaise||0),taxRate:Number(row.taxRate||0),taxType:String(row.taxType||"NONE"),shortUrl:row.shortUrl?String(row.shortUrl):null,issuedAt:new Date(String(row.issuedAt)),paidAt:row.paidAt?new Date(String(row.paidAt)):null,legalName:String(row.legalName||""),email:String(row.email||""),phone:String(row.phone||""),addressLine1:String(row.addressLine1||""),addressLine2:row.addressLine2?String(row.addressLine2):null,city:String(row.city||""),state:String(row.state||""),postalCode:String(row.postalCode||""),country:String(row.country||"India"),gstin:row.gstin?String(row.gstin):null,supplierState:row.supplierState?String(row.supplierState):null}}

function invoiceNumber(issuedAt:Date,razorpayInvoiceId:string){const fyStart=issuedAt.getMonth()>=3?issuedAt.getFullYear():issuedAt.getFullYear()-1;const fy=`${String(fyStart).slice(-2)}-${String(fyStart+1).slice(-2)}`;const suffix=crypto.createHash("sha1").update(razorpayInvoiceId).digest("hex").slice(0,8).toUpperCase();return `PPDT/${fy}/AARYVO-${suffix}`}

export async function getStoredInvoices(businessId:string){await ensureBillingTables();const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>("SELECT * FROM billing_invoice WHERE businessId = ? ORDER BY issuedAt DESC",businessId);return rows.map(rowInvoice)}
export async function getStoredInvoice(businessId:string,id:string){await ensureBillingTables();const rows=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>("SELECT * FROM billing_invoice WHERE businessId = ? AND id = ? LIMIT 1",businessId,id);return rows[0]?rowInvoice(rows[0]):null}

export async function snapshotRazorpayInvoice(businessId:string,razorpayInvoice:Record<string,unknown>){await ensureBillingTables();const razorpayInvoiceId=String(razorpayInvoice.id||"");if(!razorpayInvoiceId)return null;const existing=await prisma.$queryRawUnsafe<Array<Record<string,unknown>>>("SELECT * FROM billing_invoice WHERE razorpayInvoiceId = ? LIMIT 1",razorpayInvoiceId);if(existing[0])return rowInvoice(existing[0]);const profile=await getBillingProfile(businessId);if(!profile)return null;
 const totalPaise=Number(razorpayInvoice.amount_paid||razorpayInvoice.amount||0);if(totalPaise<=0)return null;
 const subscriptionId=razorpayInvoice.subscription_id?String(razorpayInvoice.subscription_id):null;let plan:PlanKey|"CUSTOM"="CUSTOM";if(subscriptionId){try{const sub=await razorpayRequest(`/subscriptions/${encodeURIComponent(subscriptionId)}`);plan=planFromRazorpayPlanId(String(sub?.plan_id||""))||"CUSTOM"}catch{}}
 const tax=taxBreakdownInclusive(totalPaise,profile.state,profile.country);const issuedAt=razorpayInvoice.issued_at?new Date(Number(razorpayInvoice.issued_at)*1000):new Date();const paidAt=razorpayInvoice.paid_at?new Date(Number(razorpayInvoice.paid_at)*1000):null;const id=crypto.randomUUID(),number=invoiceNumber(issuedAt,razorpayInvoiceId),status=String(razorpayInvoice.status||"paid"),currency=String(razorpayInvoice.currency||"INR");
 await prisma.$executeRawUnsafe(`INSERT INTO billing_invoice (id,businessId,razorpayInvoiceId,razorpayPaymentId,razorpaySubscriptionId,invoiceNumber,plan,status,currency,subtotalPaise,taxPaise,cgstPaise,sgstPaise,igstPaise,totalPaise,taxRate,taxType,shortUrl,issuedAt,paidAt,legalName,email,phone,addressLine1,addressLine2,city,state,postalCode,country,gstin,supplierState) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,id,businessId,razorpayInvoiceId,razorpayInvoice.payment_id?String(razorpayInvoice.payment_id):null,subscriptionId,number,plan,status,currency,tax.subtotalPaise,tax.taxPaise,tax.cgstPaise,tax.sgstPaise,tax.igstPaise,tax.totalPaise,tax.taxRate,tax.taxType,razorpayInvoice.short_url?String(razorpayInvoice.short_url):null,issuedAt,paidAt,profile.legalName,profile.email,profile.phone,profile.addressLine1,profile.addressLine2||null,profile.city,profile.state,profile.postalCode,profile.country,profile.gstin||null,tax.supplierState);
 return getStoredInvoice(businessId,id)}

export async function syncRazorpayInvoices(businessId:string,subscriptionIds:string[]){for(const subscriptionId of subscriptionIds){try{const result=await razorpayRequest(`/invoices?subscription_id=${encodeURIComponent(subscriptionId)}`);for(const invoice of Array.isArray(result?.items)?result.items:[]){const status=String(invoice.status||"").toLowerCase();if(status==="paid"||Number(invoice.amount_paid||0)>0)await snapshotRazorpayInvoice(businessId,invoice)}}catch(error){console.error("AARYVO invoice sync error",error)}}return getStoredInvoices(businessId)}
