import { randomUUID } from "crypto";
import { prisma } from "@/lib/prisma";
let ready:Promise<void>|null=null;
export function ensureEmailAnalyticsTable(){if(!ready)ready=(async()=>{await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS platform_email_log (id VARCHAR(191) PRIMARY KEY,businessId VARCHAR(191) NULL,recipient VARCHAR(320) NOT NULL,subject VARCHAR(500) NOT NULL,category VARCHAR(100) NOT NULL,source VARCHAR(50) NULL,status VARCHAR(50) NOT NULL,errorMessage TEXT NULL,sentAt DATETIME(3) NULL,openedAt DATETIME(3) NULL,openCount INT NOT NULL DEFAULT 0,clickedAt DATETIME(3) NULL,clickCount INT NOT NULL DEFAULT 0,createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),INDEX idx_email_created(createdAt),INDEX idx_email_business(businessId),INDEX idx_email_status(status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);})();return ready}
export async function createEmailLog(input:{businessId?:string|null;recipient:string;subject:string;category:string;source?:string|null}){await ensureEmailAnalyticsTable();const id=randomUUID();await prisma.$executeRawUnsafe(`INSERT INTO platform_email_log(id,businessId,recipient,subject,category,source,status) VALUES(?,?,?,?,?,?,?)`,id,input.businessId||null,input.recipient.slice(0,320),input.subject.slice(0,500),input.category.slice(0,100),input.source?.slice(0,50)||null,"QUEUED");return id}
export async function markEmailSent(id:string){await ensureEmailAnalyticsTable();await prisma.$executeRawUnsafe(`UPDATE platform_email_log SET status='SENT',sentAt=NOW(3) WHERE id=?`,id)}
export async function markEmailFailed(id:string,error:unknown){await ensureEmailAnalyticsTable();await prisma.$executeRawUnsafe(`UPDATE platform_email_log SET status='FAILED',errorMessage=? WHERE id=?`,String(error instanceof Error?error.message:error).slice(0,4000),id)}
export async function markEmailOpened(id:string){await ensureEmailAnalyticsTable();await prisma.$executeRawUnsafe(`UPDATE platform_email_log SET openedAt=COALESCE(openedAt,NOW(3)),openCount=openCount+1 WHERE id=?`,id)}
export async function markEmailClicked(id:string){await ensureEmailAnalyticsTable();await prisma.$executeRawUnsafe(`UPDATE platform_email_log SET clickedAt=COALESCE(clickedAt,NOW(3)),clickCount=clickCount+1 WHERE id=?`,id)}
export async function emailAnalyticsSummary(days=30){await ensureEmailAnalyticsTable();const d=Math.max(1,Math.min(365,Math.floor(days)));const r=await prisma.$queryRawUnsafe<Array<{total:bigint;sent:bigint;failed:bigint;opened:bigint;clicked:bigint}>>(`SELECT COUNT(*) total,SUM(status='SENT') sent,SUM(status='FAILED') failed,SUM(openCount>0) opened,SUM(clickCount>0) clicked FROM platform_email_log WHERE createdAt>=DATE_SUB(NOW(),INTERVAL ${d} DAY)`);const byCategory=await prisma.$queryRawUnsafe<Array<{category:string;total:bigint;sent:bigint;failed:bigint;opened:bigint;clicked:bigint}>>(`SELECT category,COUNT(*) total,SUM(status='SENT') sent,SUM(status='FAILED') failed,SUM(openCount>0) opened,SUM(clickCount>0) clicked FROM platform_email_log WHERE createdAt>=DATE_SUB(NOW(),INTERVAL ${d} DAY) GROUP BY category ORDER BY total DESC`);const recent=await prisma.$queryRawUnsafe<Array<{id:string;recipient:string;subject:string;category:string;source:string|null;status:string;sentAt:Date|null;openedAt:Date|null;clickedAt:Date|null;openCount:number;clickCount:number;errorMessage:string|null;createdAt:Date}>>(`SELECT id,recipient,subject,category,source,status,sentAt,openedAt,clickedAt,openCount,clickCount,errorMessage,createdAt FROM platform_email_log ORDER BY createdAt DESC LIMIT 30`);const x=r[0];return{total:Number(x?.total||0),sent:Number(x?.sent||0),failed:Number(x?.failed||0),opened:Number(x?.opened||0),clicked:Number(x?.clicked||0),byCategory:byCategory.map(v=>({...v,total:Number(v.total),sent:Number(v.sent||0),failed:Number(v.failed||0),opened:Number(v.opened||0),clicked:Number(v.clicked||0)})),recent}}
