import crypto from "node:crypto";
import { workspaceGoogleAuth } from "@/lib/google-oauth";

const TOKEN_URL="https://oauth2.googleapis.com/token",CALENDAR_API="https://www.googleapis.com/calendar/v3",SCOPE="https://www.googleapis.com/auth/calendar";
function base64Url(input:string|Buffer){return Buffer.from(input).toString("base64").replace(/=/g,"").replace(/\+/g,"-").replace(/\//g,"_");}
function cleanEnv(value?:string){return(value||"").trim().replace(/^['\"]|['\"]$/g,"");}
function credentials(){const email=cleanEnv(process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL),privateKey=cleanEnv(process.env.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY).replace(/\\n/g,"\n"),calendarId=cleanEnv(process.env.GOOGLE_CALENDAR_ID);return email&&privateKey&&calendarId?{email,privateKey,calendarId}:null;}
async function serviceAuth(){const c=credentials();if(!c)return null;const now=Math.floor(Date.now()/1000),header=base64Url(JSON.stringify({alg:"RS256",typ:"JWT"})),payload=base64Url(JSON.stringify({iss:c.email,scope:SCOPE,aud:TOKEN_URL,iat:now,exp:now+3600})),unsigned=`${header}.${payload}`,signature=crypto.sign("RSA-SHA256",Buffer.from(unsigned),c.privateKey),assertion=`${unsigned}.${base64Url(signature)}`;const r=await fetch(TOKEN_URL,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"urn:ietf:params:oauth:grant-type:jwt-bearer",assertion}),cache:"no-store"});if(!r.ok)throw new Error(`Google token request failed (${r.status})`);const d=await r.json() as{access_token?:string};if(!d.access_token)throw new Error("Google access token missing");return{token:d.access_token,calendarId:c.calendarId};}
async function authForBusiness(businessId?:string){if(businessId){const oauth=await workspaceGoogleAuth(businessId);if(oauth)return oauth;}return serviceAuth();}
export function isGoogleCalendarConfigured(){return Boolean(credentials()||process.env.GOOGLE_OAUTH_CLIENT_ID);}
export type BusyInterval={start:Date;end:Date};
export async function getGoogleBusyIntervals(timeMin:Date,timeMax:Date,businessId?:string):Promise<BusyInterval[]>{const auth=await authForBusiness(businessId);if(!auth)return[];const r=await fetch(`${CALENDAR_API}/freeBusy`,{method:"POST",headers:{Authorization:`Bearer ${auth.token}`,"Content-Type":"application/json"},body:JSON.stringify({timeMin:timeMin.toISOString(),timeMax:timeMax.toISOString(),items:[{id:auth.calendarId}]}),cache:"no-store"});if(!r.ok)throw new Error(`Google free/busy request failed (${r.status})`);const d=await r.json() as{calendars?:Record<string,{busy?:Array<{start:string;end:string}>}>};return(d.calendars?.[auth.calendarId]?.busy||[]).map(i=>({start:new Date(i.start),end:new Date(i.end)}));}
export async function createGoogleCalendarEvent(params:{businessId?:string;businessName:string;leadName:string|null;leadEmail:string|null;leadPhone:string|null;requirement:string|null;startsAt:Date;durationMinutes:number;timeZone:string}){const auth=await authForBusiness(params.businessId);if(!auth)return null;const end=new Date(params.startsAt.getTime()+params.durationMinutes*60000),description=[`AARYVO consultation for ${params.businessName}`,params.leadName?`Lead: ${params.leadName}`:null,params.leadEmail?`Email: ${params.leadEmail}`:null,params.leadPhone?`Phone: ${params.leadPhone}`:null,params.requirement?`Requirement: ${params.requirement}`:null].filter(Boolean).join("\n");const r=await fetch(`${CALENDAR_API}/calendars/${encodeURIComponent(auth.calendarId)}/events`,{method:"POST",headers:{Authorization:`Bearer ${auth.token}`,"Content-Type":"application/json"},body:JSON.stringify({summary:`AARYVO Consultation${params.leadName?` - ${params.leadName}`:""}`,description,start:{dateTime:params.startsAt.toISOString(),timeZone:params.timeZone},end:{dateTime:end.toISOString(),timeZone:params.timeZone}}),cache:"no-store"});if(!r.ok){const text=await r.text();throw new Error(`Google event creation failed (${r.status}): ${text.slice(0,300)}`);}return r.json();}
export async function listVisibleGoogleCalendars(){const auth=await serviceAuth();if(!auth)return{configured:false,configuredCalendarId:null,calendars:[]};const r=await fetch(`${CALENDAR_API}/users/me/calendarList?maxResults=100`,{headers:{Authorization:`Bearer ${auth.token}`},cache:"no-store"});if(!r.ok)throw new Error(`Calendar list request failed (${r.status})`);const d=await r.json() as{items?:Array<{id?:string;summary?:string;accessRole?:string;primary?:boolean}>};return{configured:true,configuredCalendarId:auth.calendarId,calendars:(d.items||[]).map(i=>({id:i.id||"",name:i.summary||i.id||"Unnamed calendar",accessRole:i.accessRole||null,primary:Boolean(i.primary),matchesConfiguredId:i.id===auth.calendarId}))};}
export async function testGoogleCalendarConnection(){const auth=await serviceAuth();if(!auth)return{ok:false,configured:false,error:"Google Calendar service-account variables are incomplete."};const r=await fetch(`${CALENDAR_API}/calendars/${encodeURIComponent(auth.calendarId)}`,{headers:{Authorization:`Bearer ${auth.token}`},cache:"no-store"});if(!r.ok)return{ok:false,configured:true,error:`Calendar access failed (${r.status})`};const d=await r.json() as{summary?:string;id?:string;timeZone?:string};return{ok:true,configured:true,calendar:d.summary||d.id||auth.calendarId,timeZone:d.timeZone||null};}
