import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { ArrowLeft, CalendarDays, Mail, MessageSquareText, Phone, UserRound } from "lucide-react";
import { requireSession } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import LeadStatusSelect from "./LeadStatusSelect";

type LeadPageProps={params:Promise<{id:string}>};
function statusClass(status:string){if(status==="HOT"||status==="QUALIFIED")return"bg-emerald-50 text-emerald-700";if(status==="WARM")return"bg-amber-50 text-amber-700";if(status==="WON")return"bg-blue-50 text-blue-700";if(status==="LOST")return"bg-red-50 text-red-700";return"bg-black/[.04] text-black/55";}
function formatDate(value:Date,timeZone:string){return new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short",timeZone}).format(value);}

export default async function LeadDetailPage({params}:LeadPageProps){
 const session=await requireSession(),{id}=await params;
 const membership=await prisma.businessMember.findFirst({where:{userId:session.userId},select:{businessId:true,business:{select:{name:true,bookingTimeZone:true}}}});if(!membership)redirect("/onboarding");
 const lead=await prisma.lead.findFirst({where:{id,businessId:membership.businessId},include:{conversation:{include:{messages:{orderBy:{createdAt:"asc"}}}},appointments:{orderBy:{startsAt:"desc"}}}});if(!lead)notFound();
 const timeZone=membership.business.bookingTimeZone;
 return <div className="mx-auto max-w-[1440px] pb-8">
  <div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><Link href="/dashboard/leads" className="inline-flex items-center gap-2 text-xs font-medium text-black/40 hover:text-black"><ArrowLeft size={14}/>All leads</Link><div className="mt-5 flex flex-wrap items-center gap-3"><h1 className="text-3xl font-semibold tracking-[-.04em] sm:text-4xl">{lead.name||"Anonymous prospect"}</h1><span className={`rounded-full px-3 py-1.5 text-[10px] font-semibold ${statusClass(lead.status)}`}>{lead.status}</span></div><p className="mt-2 text-sm text-black/40">Captured {formatDate(lead.createdAt,timeZone)} · {membership.business.name}</p></div><div className="flex flex-wrap items-center gap-2">{lead.phone&&<a href={`tel:${lead.phone}`} className="inline-flex items-center gap-2 rounded-full border border-black/[.08] bg-white px-4 py-2.5 text-xs font-semibold text-black/60 hover:text-black"><Phone size={14}/>Call</a>}{lead.email&&<a href={`mailto:${lead.email}`} className="inline-flex items-center gap-2 rounded-full border border-black/[.08] bg-white px-4 py-2.5 text-xs font-semibold text-black/60 hover:text-black"><Mail size={14}/>Email</a>}<LeadStatusSelect leadId={lead.id} initialStatus={lead.status}/></div></div>
  <div className="mt-7 grid gap-4 xl:grid-cols-[1fr_360px]">
   <div className="space-y-4">
    <section className="rounded-3xl border border-black/[.055] bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-xs text-black/35">Qualification</p><h2 className="mt-1 text-xl font-semibold tracking-[-.03em]">Lead summary</h2></div><div className="text-right"><p className="text-3xl font-semibold tracking-[-.05em]">{lead.score}<span className="text-base text-black/25">/100</span></p><p className="text-[10px] text-black/30">lead score</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-[#f6f7f8] p-4"><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-black/30">Requirement</p><p className="mt-2 text-sm leading-6 text-black/65">{lead.requirement||"Qualification still in progress."}</p></div><div className="rounded-2xl bg-[#f6f7f8] p-4"><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-black/30">Budget</p><p className="mt-2 text-sm font-semibold text-black/65">{lead.budget||"Not captured"}</p></div></div></section>
    <section className="rounded-3xl border border-black/[.055] bg-white p-6"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#f4f5f7] text-black/45"><MessageSquareText size={17}/></span><div><p className="text-xs text-black/35">Conversation</p><h2 className="text-xl font-semibold tracking-[-.03em]">AI transcript</h2></div></div><div className="mt-6 space-y-4">{!lead.conversation?.messages.length?<div className="rounded-2xl bg-[#f6f7f8] py-10 text-center text-sm text-black/35">No conversation transcript available.</div>:lead.conversation.messages.map((message)=>{const visitor=message.role==="user";return <div key={message.id} className={`flex ${visitor?"justify-start":"justify-end"}`}><div className={`max-w-[82%] rounded-2xl px-4 py-3 ${visitor?"bg-[#f3f4f6] text-black/70":"bg-[#111319] text-white"}`}><div className={`mb-1.5 flex items-center gap-2 text-[9px] font-semibold uppercase tracking-[.12em] ${visitor?"text-black/30":"text-white/35"}`}><span>{visitor?"Visitor":"AI employee"}</span><span>·</span><span>{formatDate(message.createdAt,timeZone)}</span></div><p className="whitespace-pre-wrap text-sm leading-6">{message.content}</p></div></div>})}</div></section>
   </div>
   <aside className="space-y-4">
    <section className="rounded-3xl border border-black/[.055] bg-white p-5"><div className="flex items-center gap-2"><UserRound size={16} className="text-black/35"/><h2 className="text-sm font-semibold">Contact</h2></div><div className="mt-5 space-y-4"><div><p className="text-[10px] uppercase tracking-[.1em] text-black/30">Name</p><p className="mt-1 text-sm font-medium">{lead.name||"Not captured"}</p></div><div><p className="text-[10px] uppercase tracking-[.1em] text-black/30">Phone</p>{lead.phone?<a href={`tel:${lead.phone}`} className="mt-1 block text-sm font-medium hover:underline">{lead.phone}</a>:<p className="mt-1 text-sm text-black/35">Not captured</p>}</div><div><p className="text-[10px] uppercase tracking-[.1em] text-black/30">Email</p>{lead.email?<a href={`mailto:${lead.email}`} className="mt-1 block break-all text-sm font-medium hover:underline">{lead.email}</a>:<p className="mt-1 text-sm text-black/35">Not captured</p>}</div></div></section>
    <section className="rounded-3xl border border-black/[.055] bg-white p-5"><div className="flex items-center gap-2"><CalendarDays size={16} className="text-black/35"/><h2 className="text-sm font-semibold">Appointments</h2></div><div className="mt-4 space-y-2">{lead.appointments.length===0?<div className="rounded-2xl bg-[#f6f7f8] px-4 py-6 text-center text-xs text-black/35">No appointments yet.</div>:lead.appointments.map((appointment)=><div key={appointment.id} className="rounded-2xl bg-[#f6f7f8] p-4"><p className="text-sm font-semibold">{formatDate(appointment.startsAt,timeZone)}</p><div className="mt-2 flex items-center justify-between"><span className="text-[10px] text-black/35">Consultation</span><span className="rounded-full bg-white px-2.5 py-1 text-[9px] font-semibold text-black/45">{appointment.status}</span></div></div>)}</div><Link href="/dashboard/appointments" className="mt-4 block text-xs font-semibold text-black/45 hover:text-black">View appointment schedule →</Link></section>
   </aside>
  </div>
 </div>;
}
