import Link from "next/link";

export const metadata = { title: "Refund Policy | AARYVO", description: "Refund policy for AARYVO subscriptions provided by PP DESIGN AND TECH." };

const sections = [
  ["Digital subscription service", "AARYVO is a digital software-as-a-service product. No physical goods are sold or delivered as part of an AARYVO subscription."],
  ["Subscription payments", "Paid AARYVO plans are recurring subscriptions. Charges provide access to the selected plan and its usage limits for the applicable billing period."],
  ["Refund eligibility", "Subscription payments are generally non-refundable once a paid billing period has started or plan access has been provided. If you believe you were charged incorrectly, charged more than once, or experienced a billing error, contact us and we will review the transaction."],
  ["Plan upgrades", "When an upgrade requires an additional or prorated payment, the higher plan entitlement may be made available after successful payment or authorization. Amounts paid for immediate upgrade access are generally non-refundable after the upgraded entitlement has been provided."],
  ["Approved refunds", "Where a refund is approved for a billing error or other eligible circumstance, it will be processed to the original payment method through our payment provider. The time taken for the amount to appear is subject to the payment provider and the customer's bank or payment method."],
  ["How to request a review", "Email ppdesignandtech@gmail.com with your AARYVO account email, business name, payment date and transaction details. Please do not send card numbers, OTPs or other sensitive payment credentials."],
];

export default function RefundPolicyPage(){return <main className="min-h-screen bg-[#f6f7fb] px-6 py-10 md:px-10"><div className="mx-auto max-w-3xl"><Link href="/" className="text-sm font-semibold tracking-[.22em]">AARYVO</Link><p className="mt-16 text-xs font-semibold uppercase tracking-[.16em] text-black/35">Legal</p><h1 className="mt-3 text-5xl font-semibold tracking-[-.05em]">Refund Policy</h1><p className="mt-4 text-sm text-black/45">Effective: 16 September 2026</p><p className="mt-8 text-base leading-7 text-black/60">AARYVO is a digital SaaS product operated by <strong>PP DESIGN AND TECH</strong>. This policy explains how refund requests for AARYVO subscription payments are handled.</p><div className="mt-10 space-y-9">{sections.map(([title,body])=><section key={title}><h2 className="text-lg font-semibold">{title}</h2><p className="mt-3 text-sm leading-7 text-black/55">{body}</p></section>)}</div><div className="mt-14 border-t border-black/[.07] pt-7 text-sm text-black/45">Billing entity: <strong className="text-black/70">PP DESIGN AND TECH</strong> · GSTIN: 07CQXPP5370D1ZB · <Link href="/contact" className="text-black underline underline-offset-4">Contact us</Link></div></div></main>}
