import { redirect } from "next/navigation";
import { logout } from "@/app/actions/auth";
import { requireSession } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export default async function DashboardPage() {
  const session = await requireSession();
  const membership = await prisma.businessMember.findFirst({ where: { userId: session.userId }, include: { business: { include: { _count: { select: { leads: true, appointments: true } } } } } });
  if (!membership) redirect("/onboarding");
  const business = membership.business;
  const stats = [["Conversations", "0", "Ready"], ["Leads captured", String(business._count.leads), "Live"], ["Appointments", String(business._count.appointments), "Live"], ["AI agent", "1", "Active"]];
  return <main className="min-h-screen bg-[#f6f7fb] p-5 md:p-8"><div className="mx-auto max-w-7xl"><header className="flex items-center justify-between"><a href="/" className="font-semibold tracking-[0.25em]">AARYVO</a><div className="flex items-center gap-3"><div className="rounded-full bg-white px-4 py-2 text-sm shadow-sm">{business.name}</div><form action={logout}><button className="rounded-full border border-black/10 px-4 py-2 text-sm">Sign out</button></form></div></header><div className="mt-12"><p className="text-sm text-black/40">AI Sales Dashboard</p><h1 className="mt-2 text-4xl font-semibold tracking-[-0.04em]">Your AI employee is ready to learn.</h1><p className="mt-3 max-w-2xl text-black/50">Workspace created successfully. Next we’ll scan {business.websiteUrl || "your business content"}, build the knowledge base and open a live agent preview.</p></div><section className="mt-8 grid gap-4 md:grid-cols-4">{stats.map(([label,value,state]) => <div key={label} className="rounded-[28px] bg-white p-6 shadow-sm"><p className="text-sm text-black/45">{label}</p><div className="mt-6 flex items-end justify-between"><p className="text-4xl font-semibold tracking-[-0.04em]">{value}</p><span className="text-sm text-emerald-600">{state}</span></div></div>)}</section><section className="mt-6 grid gap-4 lg:grid-cols-[1.4fr_.6fr]"><div className="rounded-[32px] bg-black p-8 text-white"><p className="text-sm text-white/45">Next setup step</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em]">Teach AARYVO about {business.name}.</h2><p className="mt-3 max-w-xl text-white/60">We’ll crawl approved pages from your website, extract services and FAQs, then let you review the knowledge before the agent goes live.</p><button className="mt-8 rounded-full bg-white px-5 py-3 text-sm font-medium text-black">Build knowledge base →</button></div><div className="rounded-[32px] bg-white p-8 shadow-sm"><p className="text-sm text-black/40">Workspace</p><p className="mt-4 text-xl font-semibold">{business.name}</p><p className="mt-2 break-all text-sm text-black/50">{business.websiteUrl || "No website added"}</p><div className="mt-8 rounded-2xl bg-emerald-50 px-4 py-3 text-sm text-emerald-700">AI Sales Agent · Active</div></div></section></div></main>;
}
